#!/usr/bin/env python3
"""Build runs/cost-report.md from every runs/**/result.json. Deterministic; no LLM involved.

This is the slide that ties the talk to the model-selection talk: what each agent cost, by model.
"""
import json, pathlib, collections

rows, by_model = [], collections.defaultdict(lambda: {"usd": 0.0, "in": 0, "out": 0, "runs": 0})
for p in sorted(pathlib.Path("runs").glob("**/result.json")):
    try:
        d = json.loads(p.read_text())
    except Exception:
        continue
    if isinstance(d, list):
        d = next((x for x in reversed(d) if isinstance(x, dict) and x.get("type") == "result"), {})
    u = d.get("usage") or {}
    mu = d.get("modelUsage") or {}
    for m, s in mu.items():
        by_model[m]["usd"] += s.get("costUSD", 0) or 0
        by_model[m]["in"] += (s.get("inputTokens", 0) or 0)
        by_model[m]["out"] += (s.get("outputTokens", 0) or 0)
        by_model[m]["runs"] += 1
    rows.append({
        "run": str(p.parent), "models": ",".join(sorted(mu.keys())) or "?",
        "turns": d.get("num_turns", ""), "in": u.get("input_tokens", 0) or 0,
        "cache_read": u.get("cache_read_input_tokens", 0) or 0, "out": u.get("output_tokens", 0) or 0,
        "usd": d.get("total_cost_usd", 0) or 0, "sec": round((d.get("duration_ms", 0) or 0) / 1000),
    })

out = ["# Pipeline cost report", "", "Generated by `pipeline/cost_report.py` from `runs/**/result.json`.", "",
       "| run | model(s) | turns | input tok | cache read | output tok | USD | seconds |", "|---|---|---|---|---|---|---|---|"]
tot = {"in": 0, "cache_read": 0, "out": 0, "usd": 0.0, "sec": 0}
for r in rows:
    out.append(f"| {r['run']} | {r['models']} | {r['turns']} | {r['in']:,} | {r['cache_read']:,} | {r['out']:,} | {r['usd']:.3f} | {r['sec']} |")
    for k in tot: tot[k] += r[k]
out.append(f"| **total** | | | {tot['in']:,} | {tot['cache_read']:,} | {tot['out']:,} | **{tot['usd']:.2f}** | {tot['sec']} |")
if by_model:
    out += ["", "## By model", "", "| model | stages | input tok | output tok | USD |", "|---|---|---|---|---|"]
    for m, s in sorted(by_model.items(), key=lambda kv: -kv[1]["usd"]):
        out.append(f"| {m} | {s['runs']} | {s['in']:,} | {s['out']:,} | {s['usd']:.3f} |")
out += ["", "Interactive stages run inside a Claude Code session (the research fan-out) are not captured here;",
        "check `/cost` in that session and record it in `runs/001-research-fanout/README.md`."]
pathlib.Path("runs/cost-report.md").write_text("\n".join(out) + "\n")
tsv = ["run_dir\tmodels\tturns\tinput\tcache_read\toutput\tusd\tseconds"]
tsv += ["\t".join(str(r[k]) for k in ("run", "models", "turns", "in", "cache_read", "out", "usd", "sec")) for r in rows]
pathlib.Path("runs/cost.tsv").write_text("\n".join(tsv) + "\n")  # generated, never appended to
def short_model(m):  # drop the helper-model noise and the vendor prefix for the compact view
    return ",".join(x.replace("claude-", "") for x in m.split(",") if "haiku" not in x) or "haiku"
txt = [f"{'run':<26}{'model':<12}{'turns':>6}{'output tok':>12}{'USD':>8}{'sec':>6}"]
txt += [f"{r['run']:<26}{short_model(r['models']):<12}{r['turns']:>6}{r['out']:>12,}{r['usd']:>8.2f}{r['sec']:>6}" for r in rows]
txt += [f"{'total':<26}{'':<12}{'':>6}{tot['out']:>12,}{tot['usd']:>8.2f}{tot['sec']:>6}"]
pathlib.Path("runs/cost-summary.txt").write_text("\n".join(txt) + "\n")
print(f"{len(rows)} runs, total ${tot['usd']:.2f}")
